/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoreRouteRouteImport } from './routes/_core.route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as CoreIndexRouteImport } from './routes/_core.index'
import { Route as CoreDetailRouteImport } from './routes/_core.detail'
import { Route as AuthWaitlistSplatRouteImport } from './routes/_auth/waitlist.$'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth/sign-in.$'

const CoreRouteRoute = CoreRouteRouteImport.update({
  id: '/_core',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreIndexRoute = CoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreDetailRoute = CoreDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => CoreRouteRoute,
} as any)
const AuthWaitlistSplatRoute = AuthWaitlistSplatRouteImport.update({
  id: '/waitlist/$',
  path: '/waitlist/$',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CoreIndexRoute
  '/detail': typeof CoreDetailRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/waitlist/$': typeof AuthWaitlistSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof CoreIndexRoute
  '/detail': typeof CoreDetailRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/waitlist/$': typeof AuthWaitlistSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_core': typeof CoreRouteRouteWithChildren
  '/_core/detail': typeof CoreDetailRoute
  '/_core/': typeof CoreIndexRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/_auth/waitlist/$': typeof AuthWaitlistSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detail' | '/sign-in/$' | '/sign-up/$' | '/waitlist/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detail' | '/sign-in/$' | '/sign-up/$' | '/waitlist/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_core'
    | '/_core/detail'
    | '/_core/'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
    | '/_auth/waitlist/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CoreRouteRoute: typeof CoreRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_core': {
      id: '/_core'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_core/': {
      id: '/_core/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CoreIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_core/detail': {
      id: '/_core/detail'
      path: '/detail'
      fullPath: '/detail'
      preLoaderRoute: typeof CoreDetailRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/_auth/waitlist/$': {
      id: '/_auth/waitlist/$'
      path: '/waitlist/$'
      fullPath: '/waitlist/$'
      preLoaderRoute: typeof AuthWaitlistSplatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
  AuthWaitlistSplatRoute: typeof AuthWaitlistSplatRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
  AuthWaitlistSplatRoute: AuthWaitlistSplatRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CoreRouteRouteChildren {
  CoreDetailRoute: typeof CoreDetailRoute
  CoreIndexRoute: typeof CoreIndexRoute
}

const CoreRouteRouteChildren: CoreRouteRouteChildren = {
  CoreDetailRoute: CoreDetailRoute,
  CoreIndexRoute: CoreIndexRoute,
}

const CoreRouteRouteWithChildren = CoreRouteRoute._addFileChildren(
  CoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CoreRouteRoute: CoreRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
